#  .--..--..--..--..--..--..--..--..--..--..--..--..--..--.
# / .. \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \
# \ \/\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ \/ /
#  \/ /`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'\/ /
#  / /\                                                / /\
# / /\ \   _____ _____         _______ ______  _____  / /\ \
# \ \/ /  / ____|  __ \     /\|__   __|  ____|/ ____| \ \/ /
#  \/ /  | |    | |__) |   /  \  | |  | |__  | (___    \/ /
#  / /\  | |    |  _  /   / /\ \ | |  |  __|  \___ \   / /\
# / /\ \ | |____| | \ \  / ____ \| |  | |____ ____) | / /\ \
# \ \/ /  \_____|_|  \_\/_/    \_\_|  |______|_____/  \ \/ /
#  \/ /                                                \/ /
#  / /\.--..--..--..--..--..--..--..--..--..--..--..--./ /\
# / /\ \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \.. \/\ \
# \ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `'\ `' /
#  `--'`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'`--'