name: Crates
version: '1.0.0'
main: dev.lorenz.crates.bootstrap.CratesBUkkit
api-version: '1.21'
softdepend:
  - PacketEvents
  - PlaceholderAPI
  - DecentHolograms
commands:
  crate:
    description: "Comando per gestire le crate"
  crateadmin:
    description: "Comando per gestire le crate come amministratore"
