name: Crates
version: '${version}'
main: dev.lorenz.crates.bootstrap.CratesBUkkit
api-version: '1.21'
softdepend:
  - PacketEvents
  - PlaceholderAPI

commands:
  crate:
    description: "Comando per gestire le crate"
